parameters:
    #parameter_name: value

services:
    app.stream.sample.service:
        class: AppBundle\Service\StreamSamplerService

    app.random.string.generator:
        class: AppBundle\Util\StringGenerator
